# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: ReplaceTokens@3
  inputs:
    targetFiles: '**/application.yml'
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    escapeType: 'none'
    actionOnMissing: 'warn'
    enableTransforms: true
    useLegacyPattern: false
    verbosity: 'detailed'
    tokens:
    user: $(ManuelMata_LIB.user)
    pass: $(ManuelMata_LIB.pass) 


- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
