# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

variables:
  - group: ManuelMata_LIB

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: ReplaceTokens@5
  inputs:
   targetFiles: '**/application.yml'
   encoding: 'auto'
   tokenPattern: 'default'
   writeBOM: true
   actionOnMissing: 'warn'
   keepToken: false
   actionOnNoFiles: 'continue'
   enableTransforms: false
   enableRecursion: false
   useLegacyPattern: false
   enableTelemetry: true



- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.StagingDirectory)'
    ArtifactName: 'RESP001'
    publishLocation: 'Container'